#!/bin/bash

# glisser-editer
# USAGE: gled

# clear
# set -x

function gledUpdate {

  content=$1
  echo "processing "$content
  
  detox -r $content
  
  docw=1240                     # docsize
  doch=1754                     # A4 - 300dpi = 2480x3508 | 150 dpi = 2480x3508

  archive="$content/archives"   # keeping all submission ordered by date
  inbox="$content/inbox"        # where the new files are uploaded
  printers="$content/printers"  # printer files list
  steps="$content/steps"        # every steps of the image in jpegs
  trash="$content/trash"        # an incremental clone of the inbox
  last="$steps/last.jpg"        # the current wall state
  lastweb="$steps/last.web.jpg" # web version of the current state

  for doc in `find $inbox \( -iname \*.png -o -iname \*.jpg -o -iname \*.jpeg -o -iname \*.gif \) -type f | xargs ls -rt`
  do
    
    box=$(basename $(dirname $doc))   # contribution path
    ybox=${box:0:1}                   # sheet line number                   
    xbox=${box:2:1}                   # sheet column
  
    docname=$(basename $doc)          # contribution file
  
    # get contribution timestamp
    filetime=$(perl -MPOSIX -le 'print strftime "%s",localtime ((stat $ARGV[0])[9])' $doc)
    filetimehuman=$(perl -MPOSIX -le 'print strftime "%d/%m/%Y %H:%M",localtime ((stat $ARGV[0])[9])' $doc)
    
    now=$(date +"%y.%m.%d-%H.%M.%S")
    printf "\n| $ybox:$xbox | $filetimehuman | $docname\n\n"
    
    previous=$steps"/"$(ls $steps | sort -nr | head -1)
    
    # resize and archive
  
    archiveName="$now-$filetime.$ybox-$xbox.$docname.jpg" #name of the archive file
  
    convert -format jpg -auto-orient -gravity center -resize $docw"x"$doch^ -gravity center -extent $docw"x"$doch -density 100x100 $doc \
    -pointsize 35 -undercolor '#fff' -fill Black \
    -gravity north -annotate +0+35 " $ybox - $xbox " \
	-pointsize 15 \
    -gravity South  -annotate +0+35 " $filetimehuman " \
    $archive"/"$archiveName
  
    # archive optim
    jpegoptim $archive"/"$archiveName
    
    # add current contribution to last step
    step="$steps/$now-$filetime.$docname.jpg"
    composite $archive"/"$archiveName -geometry "+$((docw*xbox))+$((doch*ybox))" $previous $step
  
    # move form inbox to trash
  
    # step optim
    jpegoptim $step
    
    # update last step
    rm $last
    rm $lastweb
    cp $step $last
    
    convert -resize 25% $last $lastweb
  
    # generate printable version (pdf)
    pdf="$printers/$now-$filetime.$docname.temp.pdf"
    convert -format pdf $archive"/"$archiveName $pdf
  
    # copy printable version for every printers
    for printer in `find $printers -type d`
    do
      #echo "add to queue : $( basename $printer) "
      cp $pdf "$printer/$now.pdf"  
    done
    
    rm $pdf
    mv $doc "$trash/$box/$docName"
  
  done
}

#gled-init -l 4 -c 4 -w 1240 -h 1754 "gled.conciergerie"

for poster in `find $(pwd) -name "gled*" -type d`
do
  gledUpdate $poster
done

echo "-"
echo $(date +"%y/%m/%d @ %k:%M:%S") " updated !"
echo "-"