#!/bin/bash
# USAGE: gled-loop frequence

while true; do
    gled
    
    for (( i=$1; i>0; i--)); do
      sleep 1 &
      printf "Lanch gled in $i s \r"
      wait
    done

    printf "              \r"
done