#!/bin/bash

# glisser-editer
# USAGE: gled

# clear
# set -x

function gledUpdate {

  content=$1
  echo "processing "$content
  
  detox -vr $content
  
  docw=3508                    # docsize
  doch=2480                    # A4 - 300dpi = 2480x3508

  archive="$content/archives"   # keeping all submission ordered by date
  inbox="$content/inbox"        # where the new files are uploaded
  printers="$content/printers"  # printer files list
  steps="$content/steps"        # every steps of the image in jpegs
  trash="$content/trash"        # an incremental clone of the inbox
  last="$steps/last.jpg"        # the current wall state
  lastweb="$steps/last.web.jpg"  

  for doc in `find $inbox \( -iname \*.png -o  -iname \*.pdf -o -iname \*.jpg \) -type f | xargs ls -rt`
  do
  
    box=$(basename $(dirname $doc))  # contribution path
    ybox=${box:0:1}                   # sheet line number                   
    xbox=${box:2:1}                   # sheet column
  
    docname=$(basename $doc)             # contribution file
  
  
    # get contribution timestamp
    filetime=$(perl -MPOSIX -le 'print strftime "%s",localtime ((stat $ARGV[0])[9])' $doc)
    filetimehuman=$(perl -MPOSIX -le 'print strftime "%d/%m/%Y %H:%M",localtime ((stat $ARGV[0])[9])' $doc)
    
    now=$(date +"%y.%m.%d-%k.%M.%S")
    echo "$ybox:$xbox ($docname) @$filetimehuman"
    
    # resize and archive
  
    archiveName="$now-$filetime.$ybox-$xbox.$docname" #name of the archive file
  
    convert -format jpg -gravity center -resize $docw"x"$doch -extent $docw"x"$doch $doc \
    -gravity north -geometry +0+500 -pointsize 30 \
    -stroke '#fff' -strokewidth 3 -annotate 0 "$ybox:$xbox [${docname:0:50}] @$filetimehuman" \
    -stroke none   -fill blue    -annotate 0 "$ybox:$xbox [${docname:0:50}] @$filetimehuman" \
    $archive"/"$archiveName
  
    # archive optim
    jpegoptim $archive"/"$archiveName
    
    # add current contribution to last step
    step="$steps/$now-$filetime.$docname.jpg"
    composite $archive"/"$archiveName -geometry "+$((docw*xbox))+$((doch*ybox))" $last $step
  
    # move form inbox to trash
    mv $doc "$trash/$box/$docName"
  
    # step optim
    jpegoptim $step
    
    # update last step
    rm $last
    rm $lastweb
    cp $step $last
    
    convert -resize 35% $last $lastweb
  
    # generate printable version (pdf)
    pdf="$printers/$now-$filetime.$docname.temp.pdf"
    convert -format pdf $archive"/"$archiveName $pdf
  
    # copy printable version for every printers
    for printer in `find $printers -type d`
    do
      #echo "add to queue : $( basename $printer) "
      cp $pdf "$printer/$now.pdf"  
    done
    
    rm $pdf
  
  done
}
#gled-init gled-img-2 4 2

for poster in `find $(pwd) -name "gled*" -type d`
do
  gledUpdate $poster
done

echo "-"
echo $(date +"%y/%m/%d @ %k:%M:%S") " updated !"
echo "-"