#!/bin/bash
# USAGE: gled-loop frequence

while true; do
    gled
    
    now=$(date +"%y.%m.%d-%H.%M")
    capture=${now:0:13}
    capturepath=~/Dropbox/dcfvg-gled/gled.conciergerie/captures
    
    for (( i=$1; i>0; i--)); do
      sleep 1 &
      printf "Lanch gled in $i s \r"
      wait
    done
    imagesnap $capturepath/$capture.png
    cp $capturepath/$capture.png $capturepath/last.png
    
    printf "              \r"
done