#!/bin/bash
# USAGE: gled-loop frequence

while true; do
    gled
    
    now=$(date +"%y.%m.%d-%H.%M")
    capture=${now:0:13}
    capturepath=~/Dropbox/dcfvg-gled/gled.conciergerie/captures
    
    for (( i=$1; i>0; i--)); do
      sleep 1 &
      printf "Lanch gled in $i s \r"
      wait
    done
    
    
    # video capture 
    imagesnap $capturepath/$capture.jpg
	  jpegoptim $capturepath/$capture.jpg
	
    rm $capturepath/live.jpg
    cp $capturepath/$capture.jpg $capturepath/live.jpg
    
    # print file
    gled-print ~/Dropbox/dcfvg-gled/gled.conciergerie/printers/conciergerie
    
    printf "              \r"
done